export const genreList: Array<string> = [
  "n/a",
  "Animals",
  "Antiques",
  "Art",
  "Astronomy",
  "Atlas",
  "Australiana",
  "Australian Wildlife",
  "Automotive",
  "Biggles",
  "Biographies",
  "Buddhism",
  "Bush Survival",
  "Business / Sales",
  "Childrens",
  "Childrens Non-Fiction",
  "Childrens Vintage",
  "Classics",
  "Collectibles",
  "Comics",
  "Conspiracy",
  "Contempory Romance",
  "Cooking",
  "Craft",
  "Crime",
  "DIY",
  "Enid Blyton",
  "Erotica",
  "Exploration",
  "Farming",
  "Fashion",
  "Folio",
  "Gardening",
  "General",
  "Health / Fitness",
  "Health Awareness",
  "Historical Romance",
  "History",
  "Horror",
  "Humor",
  "Indigenous",
  "Language",
  "Manga",
  "Medicine / Anatomy",
  "Mining / Gold",
  "Misc",
  "Music",
  "Mythology / Astrology",
  "Natural Health",
  "New Age",
  "Non-Fiction Front",
  "Non-Fiction Back",
  "Ocean Creatures",
  "Parenting",
  "Philosophy",
  "Photography",
  "Poetry & Plays",
  "Psychology",
  "Religion",
  "Royals",
  "Sailing",
  "Science / Natural History",
  "Sci-Fi / Fantasy",
  "Sport",
  "Suspense",
  "Technical",
  "Technology",
  "Trains",
  "Travel",
  "True Crime",
  "Urban",
  "Vehicles",
  "WA History",
  "War / Spy Fiction",
  "War Non-Fiction",
  "Westerns",
  "World History",
  "Yoga",
  "Young Adult General",
  "Young Adult Fantasy",
];
