export const genreList: Array<string> = [
  "n/a",
  "African History",
  "American History",
  "Animals",
  "Animal Tales",
  "Antiques",
  "Art",
  "Asian History",
  "Astronomy",
  "Atlas",
  "Australiana",
  "Australian Bios / Memoir",
  "Australian Wildlife",
  "Biggles",
  "Biographies",
  "Birds",
  "British History",
  "Buddhism",
  "Bush Survival",
  "Business / Sales",
  "Childrens",
  "Childrens Non-Fiction",
  "Childrens Vintage",
  "China History",
  "Classics",
  "Comics",
  "Conspiracy",
  "Contempory Romance",
  "Cooking",
  "Craft",
  "Crime",
  "Death / Grieving",
  "Diet Fitness",
  "Dogs",
  "Enid Blyton",
  "Enviromental",
  "Erotica",
  "European History",
  "Exploration",
  "Farming",
  "Fashion",
  "Feminism",
  "Folio",
  "Gardening",
  "General",
  "Games Books",
  "Greek / Roman History",
  "Historical Romance",
  "History",
  "Horror",
  "Horses",
  "Humor",
  "Indigenous",
  "Insects",
  "Journalism",
  "Language",
  "Manga",
  "Massage",
  "Medicine / Anatomy",
  "Middle Eastern History",
  "Mining / Gold",
  "Misc",
  "Mythology / Astrology",
  "Natural Health",
  "New Age",
  "Non-Fiction Front",
  "Non-Fiction Back",
  "Ocean Creatures",
  "Parenting",
  "Pet Care",
  "Philosophy",
  "Photography",
  "Poetry & Plays",
  "Psychology",
  "Religion",
  "Reptiles",
  "Royals",
  "Sailing",
  "Self-Help",
  "Science / Natural History",
  "Sci-Fi / Fantasy",
  "Sociology",
  "Sport",
  "Suspense",
  "Tai Chi",
  "Technical",
  "Technology",
  "Trains",
  "Travel",
  "True Crime",
  "Urban",
  "Vechiles",
  "WA History",
  "War / Spy Fiction",
  "War Non-Fiction",
  "Westerns",
  "World History",
  "Yoga",
  "Young Adult General",
  "Young Adult Fantasy",
];
