export const genreList: Array<string> = [
  'General',
  'Crime',
  'War / Spy Fiction',
  'Sci-Fi / Fantasy',
  'Horror',
  'Contempory Romance',
  'Historical Romance',
  'History',
  'Non-Fiction Front',
  'Non-Fiction Back',
  'War Non-Fiction',
  'Australiana',
  'Biographies',
  'Poetry & Plays',
  'Urban',
  'Childrens',
  'Suspense',
  'Classics',
  'Comics',
  'Art / Photography',
  'Childrens Vintage',
  'Travel',
  'Science',
  'Sport',
  'Technical',
  'Misc',
  'n/a',
];
